package il.co.singleton;

//This singleton is generated by Intellij Idea.

public class IntellijBaseGeneratedSingleton {
    private static IntellijBaseGeneratedSingleton ourInstance = new IntellijBaseGeneratedSingleton();

    public static IntellijBaseGeneratedSingleton getInstance() {
        return ourInstance;
    }

    private IntellijBaseGeneratedSingleton() {
    }
}
